version: '3.8'

services:
  spotiflac:
    build: .
    image: spotiflac-server:latest
    container_name: spotiflac
    restart: unless-stopped
    ports:
      # Runtipi port çakışmalarını önlemek için APP_PORT değişkenini otomatik atar
      - "${APP_PORT}:5000"
    volumes:
      # Runtipi'nin global Medya klasörüne köprü kuruyoruz
      - ${MEDIA_DIR}/Music:/downloads
      - ${MEDIA_DIR}/Music:/app/downloads 
    environment:
      # Runtipi bu bilgileri senin sisteminden otomatik çeker
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      # Runtipi'nin ana ağına bağlanıyoruz ki arayüzden erişilebilsin
      - tipi_main_network

networks:
  tipi_main_network:
    external: true